In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 12],
    [2, 13],
    [3, 14],
    [4, 15],
    [5, 16]
])

In [5]:
print(X)

[[ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]
 [ 5 16]]


In [6]:
y = np.array([20, 25, 32, 40, 48])
print(y)

[20 25 32 40 48]


In [8]:
X_b = np.c_[np.ones((X.shape[0], 1)), X]
print(X_b)

[[ 1.  1. 12.]
 [ 1.  2. 13.]
 [ 1.  3. 14.]
 [ 1.  4. 15.]
 [ 1.  5. 16.]]


In [11]:
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
print(theta)

LinAlgError: Singular matrix